[package]
name = "tree-sitter-logrotate"
description = "Logrotate configuration and state grammars for Tree-sitter"
version = "0.2.0"
authors = ["Brandon Williams"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "logrotate"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/willibrandon/tree-sitter-logrotate"
homepage = "https://willibrandon.github.io/tree-sitter-logrotate/"
documentation = "https://willibrandon.github.io/tree-sitter-logrotate/"
edition = "2024"
rust-version = "1.85"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "/grammar.js",
  "queries/*",
  "src/*.c",
  "src/*.json",
  "src/tree_sitter/*.h",
  "src/state/grammar.js",
  "src/state/tree-sitter.json",
  "src/state/queries/*.scm",
  "src/state/src/*.c",
  "src/state/src/*.json",
  "src/state/src/tree_sitter/*.h",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.12"
