/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_logrotatestate_DASH_DASHversion = 1,
  anon_sym_SPACE = 2,
  sym_version = 3,
  aux_sym_record_token1 = 4,
  anon_sym_DQUOTE = 5,
  aux_sym_quoted_path_token1 = 6,
  sym_escape_sequence = 7,
  anon_sym_DASH = 8,
  anon_sym_COLON = 9,
  aux_sym_year_token1 = 10,
  sym_invalid_record = 11,
  sym__newline = 12,
  sym_source_file = 13,
  sym_header = 14,
  sym_record = 15,
  sym_quoted_path = 16,
  sym_timestamp = 17,
  sym_year = 18,
  sym_month = 19,
  sym_day = 20,
  sym_hour = 21,
  sym_minute = 22,
  sym_second = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym_quoted_path_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_logrotatestate_DASH_DASHversion] = "header_keyword",
  [anon_sym_SPACE] = " ",
  [sym_version] = "version",
  [aux_sym_record_token1] = "record_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_path_token1] = "quoted_path_token1",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_DASH] = "-",
  [anon_sym_COLON] = ":",
  [aux_sym_year_token1] = "year_token1",
  [sym_invalid_record] = "invalid_record",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym_record] = "record",
  [sym_quoted_path] = "quoted_path",
  [sym_timestamp] = "timestamp",
  [sym_year] = "year",
  [sym_month] = "month",
  [sym_day] = "day",
  [sym_hour] = "hour",
  [sym_minute] = "minute",
  [sym_second] = "second",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_quoted_path_repeat1] = "quoted_path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_logrotatestate_DASH_DASHversion] = anon_sym_logrotatestate_DASH_DASHversion,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_version] = sym_version,
  [aux_sym_record_token1] = aux_sym_record_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_path_token1] = aux_sym_quoted_path_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_year_token1] = aux_sym_year_token1,
  [sym_invalid_record] = sym_invalid_record,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym_record] = sym_record,
  [sym_quoted_path] = sym_quoted_path,
  [sym_timestamp] = sym_timestamp,
  [sym_year] = sym_year,
  [sym_month] = sym_month,
  [sym_day] = sym_day,
  [sym_hour] = sym_hour,
  [sym_minute] = sym_minute,
  [sym_second] = sym_second,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_quoted_path_repeat1] = aux_sym_quoted_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_logrotatestate_DASH_DASHversion] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_record_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_path_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_year_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_invalid_record] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_path] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym_year] = {
    .visible = true,
    .named = true,
  },
  [sym_month] = {
    .visible = true,
    .named = true,
  },
  [sym_day] = {
    .visible = true,
    .named = true,
  },
  [sym_hour] = {
    .visible = true,
    .named = true,
  },
  [sym_minute] = {
    .visible = true,
    .named = true,
  },
  [sym_second] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_day = 1,
  field_hour = 2,
  field_keyword = 3,
  field_minute = 4,
  field_month = 5,
  field_path = 6,
  field_second = 7,
  field_timestamp = 8,
  field_version = 9,
  field_year = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_day] = "day",
  [field_hour] = "hour",
  [field_keyword] = "keyword",
  [field_minute] = "minute",
  [field_month] = "month",
  [field_path] = "path",
  [field_second] = "second",
  [field_timestamp] = "timestamp",
  [field_version] = "version",
  [field_year] = "year",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 3},
  [4] = {.index = 7, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 0},
    {field_version, 2},
  [2] =
    {field_path, 0},
    {field_timestamp, 2},
  [4] =
    {field_day, 4},
    {field_month, 2},
    {field_year, 0},
  [7] =
    {field_day, 4},
    {field_hour, 6},
    {field_minute, 8},
    {field_month, 2},
    {field_second, 10},
    {field_year, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        '\t', 38,
        '\n', 72,
        '\r', 1,
        ' ', 36,
        '"', 39,
        '-', 42,
        ':', 43,
        '\\', 70,
        'l', 58,
        '1', 37,
        '2', 37,
      );
      if (lookahead != 0) ADVANCE(71);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(72);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(35);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == 'l') ADVANCE(17);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(23);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 14:
      if (lookahead == 'g') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 28:
      if (lookahead == 'v') ADVANCE(12);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(41);
      END_STATE();
    case 31:
      if (eof) ADVANCE(33);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(39);
      if (lookahead != 0) ADVANCE(71);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead == '1' ||
          lookahead == '2') ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_logrotatestate_DASH_DASHversion);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_version);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_record_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_quoted_path_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_year_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == '-') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'a') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'a') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'e') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'e') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'g') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'i') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'n') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'o') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'o') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'o') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'r') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'r') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 's') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 's') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 't') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 't') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 't') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 't') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead == 'v') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(41);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_invalid_record);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 31},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 32},
  [11] = {.lex_state = 32},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 32},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 32},
  [27] = {.lex_state = 32},
  [28] = {.lex_state = 32},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 32},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 32},
  [34] = {.lex_state = 32},
  [35] = {.lex_state = 32},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_logrotatestate_DASH_DASHversion] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [aux_sym_record_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_invalid_record] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(24),
    [sym_header] = STATE(6),
    [anon_sym_logrotatestate_DASH_DASHversion] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      sym_invalid_record,
    STATE(12), 1,
      sym_record,
    STATE(27), 1,
      sym_quoted_path,
    ACTIONS(5), 2,
      ts_builtin_sym_end,
      sym__newline,
  [17] = 3,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    STATE(5), 1,
      aux_sym_quoted_path_repeat1,
    ACTIONS(13), 2,
      aux_sym_quoted_path_token1,
      sym_escape_sequence,
  [28] = 3,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      aux_sym_quoted_path_repeat1,
    ACTIONS(17), 2,
      aux_sym_quoted_path_token1,
      sym_escape_sequence,
  [39] = 3,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(5), 1,
      aux_sym_quoted_path_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_path_token1,
      sym_escape_sequence,
  [50] = 3,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 1,
      sym__newline,
    STATE(7), 1,
      aux_sym_source_file_repeat1,
  [60] = 3,
    ACTIONS(26), 1,
      sym__newline,
    ACTIONS(28), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      aux_sym_source_file_repeat1,
  [70] = 3,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    ACTIONS(32), 1,
      sym__newline,
    STATE(8), 1,
      aux_sym_source_file_repeat1,
  [80] = 3,
    ACTIONS(35), 1,
      aux_sym_year_token1,
    STATE(14), 1,
      sym_timestamp,
    STATE(33), 1,
      sym_year,
  [90] = 1,
    ACTIONS(37), 3,
      ts_builtin_sym_end,
      anon_sym_DASH,
      sym__newline,
  [96] = 2,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      sym__newline,
  [104] = 1,
    ACTIONS(30), 2,
      ts_builtin_sym_end,
      sym__newline,
  [109] = 1,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      sym__newline,
  [114] = 1,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      sym__newline,
  [119] = 2,
    ACTIONS(47), 1,
      aux_sym_year_token1,
    STATE(23), 1,
      sym_month,
  [126] = 2,
    ACTIONS(49), 1,
      aux_sym_year_token1,
    STATE(11), 1,
      sym_day,
  [133] = 2,
    ACTIONS(51), 1,
      aux_sym_year_token1,
    STATE(29), 1,
      sym_hour,
  [140] = 2,
    ACTIONS(53), 1,
      aux_sym_year_token1,
    STATE(32), 1,
      sym_minute,
  [147] = 2,
    ACTIONS(55), 1,
      aux_sym_year_token1,
    STATE(21), 1,
      sym_second,
  [154] = 1,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      sym__newline,
  [159] = 1,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym__newline,
  [164] = 1,
    ACTIONS(61), 1,
      anon_sym_COLON,
  [168] = 1,
    ACTIONS(63), 1,
      anon_sym_DASH,
  [172] = 1,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
  [176] = 1,
    ACTIONS(67), 1,
      anon_sym_SPACE,
  [180] = 1,
    ACTIONS(69), 1,
      aux_sym_record_token1,
  [184] = 1,
    ACTIONS(71), 1,
      aux_sym_record_token1,
  [188] = 1,
    ACTIONS(73), 1,
      anon_sym_DASH,
  [192] = 1,
    ACTIONS(75), 1,
      anon_sym_COLON,
  [196] = 1,
    ACTIONS(77), 1,
      sym_version,
  [200] = 1,
    ACTIONS(79), 1,
      anon_sym_COLON,
  [204] = 1,
    ACTIONS(81), 1,
      anon_sym_COLON,
  [208] = 1,
    ACTIONS(83), 1,
      anon_sym_DASH,
  [212] = 1,
    ACTIONS(85), 1,
      aux_sym_record_token1,
  [216] = 1,
    ACTIONS(87), 1,
      anon_sym_DASH,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 17,
  [SMALL_STATE(4)] = 28,
  [SMALL_STATE(5)] = 39,
  [SMALL_STATE(6)] = 50,
  [SMALL_STATE(7)] = 60,
  [SMALL_STATE(8)] = 70,
  [SMALL_STATE(9)] = 80,
  [SMALL_STATE(10)] = 90,
  [SMALL_STATE(11)] = 96,
  [SMALL_STATE(12)] = 104,
  [SMALL_STATE(13)] = 109,
  [SMALL_STATE(14)] = 114,
  [SMALL_STATE(15)] = 119,
  [SMALL_STATE(16)] = 126,
  [SMALL_STATE(17)] = 133,
  [SMALL_STATE(18)] = 140,
  [SMALL_STATE(19)] = 147,
  [SMALL_STATE(20)] = 154,
  [SMALL_STATE(21)] = 159,
  [SMALL_STATE(22)] = 164,
  [SMALL_STATE(23)] = 168,
  [SMALL_STATE(24)] = 172,
  [SMALL_STATE(25)] = 176,
  [SMALL_STATE(26)] = 180,
  [SMALL_STATE(27)] = 184,
  [SMALL_STATE(28)] = 188,
  [SMALL_STATE(29)] = 192,
  [SMALL_STATE(30)] = 196,
  [SMALL_STATE(31)] = 200,
  [SMALL_STATE(32)] = 204,
  [SMALL_STATE(33)] = 208,
  [SMALL_STATE(34)] = 212,
  [SMALL_STATE(35)] = 216,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_path_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_path_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timestamp, 5, 0, 3),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 3, 0, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_second, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timestamp, 11, 0, 4),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hour, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_path, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_year, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_minute, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_path, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_month, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_logrotate_state(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "logrotate_state",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
