HISTFILE="${HOME}/.cache/zsh/history"
HISTSIZE=10000
SAVEHIST=10000
mkdir -p "${HISTFILE:h}"

setopt append_history hist_ignore_all_dups prompt_subst share_history
bindkey -e

autoload -Uz add-zsh-hook compinit vcs_info
compinit -d "${HOME}/.cache/zsh/zcompdump"
zstyle ':vcs_info:*' enable git

_tree_sitter_logrotate_prompt() {
  local exit_status=$?
  local dirty_count
  local repo_root

  repo_root=$(git rev-parse --show-toplevel 2>/dev/null)
  if [[ -n "${repo_root}" && "${PWD}" == "${repo_root}" ]]; then
    typeset -g TREE_SITTER_LOGROTATE_LOCATION=''
  elif [[ -n "${repo_root}" && "${PWD}" == "${repo_root}"/* ]]; then
    typeset -g TREE_SITTER_LOGROTATE_LOCATION=" %F{39}${PWD#${repo_root}/}%f"
  else
    typeset -g TREE_SITTER_LOGROTATE_LOCATION=' %F{39}%1~%f'
  fi

  dirty_count=$(git status --porcelain=v1 2>/dev/null | wc -l)

  if (( dirty_count )); then
    zstyle ':vcs_info:git:*' formats ' %F{178}%b%f'
    typeset -g TREE_SITTER_LOGROTATE_DIRTY=" %F{178}!${dirty_count}%f"
  else
    zstyle ':vcs_info:git:*' formats ' %F{76}%b%f'
    typeset -g TREE_SITTER_LOGROTATE_DIRTY=''
  fi

  vcs_info
  if (( exit_status == 0 )); then
    typeset -g TREE_SITTER_LOGROTATE_PROMPT_CHAR='%F{76}❯%f'
  else
    typeset -g TREE_SITTER_LOGROTATE_PROMPT_CHAR='%F{196}❯%f'
  fi
}

add-zsh-hook precmd _tree_sitter_logrotate_prompt

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

PROMPT='%F{245}%m%f${TREE_SITTER_LOGROTATE_LOCATION}${vcs_info_msg_0_}${TREE_SITTER_LOGROTATE_DIRTY} ${TREE_SITTER_LOGROTATE_PROMPT_CHAR} '
